name: Windows

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Visual Studio shell
        uses: egor-tensin/vs-shell@v1

      - name: Setup GraalVM environment
        uses: gluonhq/setup-graalvm@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Make staging directory
        run: mkdir staging

      - name: Gluon Build
        run: mvn -Pdesktop gluonfx:build gluonfx:package

      - name: Copy native image to staging
        run: cp -r target/gluonfx/x86_64-windows/*.exe staging

      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: Package
          path: staging